version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Building Ktor project"
      - ./gradlew clean
      - mkdir -p certs
      - aws s3 cp s3://urepair/auths/authentication.properties src/main/resources/
      - aws s3 cp s3://urepair/auths/dbconfig.properties src/main/resources/
      - aws s3 cp s3://urepair/auths/application.conf src/main/resources/
      - aws s3 cp s3://urepair/auths/server.jks ./
      - aws s3 cp s3://urepair/auths/server.crt certs/server.crt
      - aws s3 cp s3://urepair/auths/server.key certs/server.key
  build:
    commands:
      - ./gradlew buildFatJar
  post_build:
    commands:
      - mkdir -p .platform/nginx/conf.d
      - mkdir -p .ebextensions/
      - aws s3 cp s3://urepair/auths/https.conf .platform/nginx/conf.d/
      - aws s3 cp s3://urepair/auths/https-instance.yml .ebextensions/https-instance.config
      - aws s3 cp s3://urepair/auths/https-instance-single.yml .ebextensions/https-instance-single.config
      - cp build/libs/backend-all.jar ./
artifacts:
  files:
    - backend-all.jar
    - .platform/**/*
    - certs/**/*
    - server.jks
    - .ebextensions/**/*
  discard-paths: no
