version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Building Ktor project"
      - ./gradlew clean
      - mkdir -p certs
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/authentication.properties src/main/resources/
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/dbconfig.properties src/main/resources/
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/keystore.properties src/main/resources/
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/application.conf src/main/resources/
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/server.jks src/main/resources/
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/server.jks ./
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/https-instance.config src/main/resources/.ebextensions/
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/server.crt certs/server.crt
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/server.key certs/server.key
  build:
    commands:
      - ./gradlew buildFatJar
artifacts:
  files:
    - build/libs/backend-all.jar
    - .ebextensions/
    - certs/**/*
    - server.jks
  discard-paths: yes
