version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Building Ktor project"
      - ./gradlew clean
  build:
    commands:
      - ./gradlew buildFatJar
artifacts:
  files:
    - build/libs/backend-all.jar
  discard-paths: yes
