version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Building Ktor project"
      - ./gradlew clean
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/authentication.properties src/main/resources/
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/dbconfig.properties src/main/resources/
  build:
    commands:
      - ./gradlew buildFatJar
artifacts:
  files:
    - build/libs/backend-all.jar
  discard-paths: yes
