version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - ./gradlew build
  post_build:
    commands:
      - cp build/libs/*.jar backend-0.0.1.jar
artifacts:
  files:
    - backend-0.0.1.jar
    - Procfile
