version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Building Ktor project"
      - ./gradlew clean
      - aws s3 cp s3://urepair/auths/https-instance.yml .ebextensions/https-instance.config
      - aws s3 cp s3://urepair/auths/urepair_me.jks ./
      - cd src/main/resources && mkdir react-app && cd ../../../
      - git clone https://github.com/CS320-Team-6/frontend.git
      - cd frontend
      # Edit the following line to deploy new frontend version
      - git checkout tags/0.1.2
      - npm i
  build:
    commands:
       - npm run build && cd ../
       - cp -r frontend/build/* src/main/resources/react-app/
       - ./gradlew buildFatJar
  post_build:
    commands:
      - cp build/libs/backend-all.jar ./
artifacts:
  files:
    - backend-all.jar
    - urepair_me.jks
  discard-paths: no
