version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Building Ktor project"
      - SECRET_VALUE=$(aws secretsmanager get-secret-value --secret-id urepair/httpsInstance --query SecretString --output text)
      - echo "$SECRET_VALUE" > .ebextensions/https-instance.config
      - aws s3 cp s3://urepair/auths/urepair_me.jks ./
      - cd src/main/resources && mkdir react-app && cd ../../../
      - git clone https://github.com/CS320-Team-6/frontend.git
      - cd frontend
      # Edit the following line to deploy new frontend version
      - git checkout tags/0.1.4
      - npm i
      - npm run build && cd ../
      - cp -r frontend/build/* src/main/resources/react-app/
      - ./gradlew clean
  build:
    commands:
       - ./gradlew buildFatJar
  post_build:
    commands:
      - cp build/libs/backend-all.jar ./
artifacts:
  files:
    - backend-all.jar
    - .platform/**/*
    - urepair_me.jks
    - .ebextensions/**/*
  discard-paths: no
