version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo "Building Ktor project"
      - ./gradlew clean
  build:
    commands:
      - ./gradlew buildFatJar
  post_build:
    commands:
      - aws s3 cp s3://urepair-test-john2-pipeline/auths/* ./
artifacts:
  files:
    - build/libs/backend-all.jar
    - authentication.properties
    - dbconfig.properties
  discard-paths: yes
